version = 2
root = "/var/lib/containerd"
state = "/run/containerd"
oom_score = 0

disabled_plugins = [
    "io.containerd.runtime.v2.task",
    "io.containerd.runtime.v1.linux", 
    "io.containerd.snapshotter.v1.devmapper", 
    "io.containerd.grpc.v1.cri", 
    "io.containerd.runtime.v2.shim", 
    "io.containerd.sandbox.controller.v1.local", 
    "io.containerd.service.v1.tasks-service",
    "io.containerd.grpc.v1.sandbox-controllers",
    "io.containerd.grpc.v1.tasks",
    "io.containerd.internal.v1.restart",
    "io.containerd.grpc.v1.events",
    "io.containerd.grpc.v1.containers",
    "io.containerd.monitor.v1.cgroups",
    "io.containerd.service.v1.containers-service",
    "io.containerd.snapshotter.v1.zfs",
    "io.containerd.snapshotter.v1.btrfs",
    "io.containerd.snapshotter.v1.aufs",
]

[grpc]
    address = "/run/containerd/containerd.sock"
    uid = 0
    gid = 0

[debug]
    address = "/run/containerd/debug.sock"
    uid = 0
    gid = 0
    level = "warn"
