runtime:
  engine: containerd
  socketPath: /run/containerd/containerd.sock
kubeletRoot: /var/lib/kubelet
snapshotRoot: /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs
logLevel: 4
enableDaemonImageCredentialCache:
enableAsyncPull: false
asyncPullTimeout: "10m"
asyncPullRateLimit: 1
asyncPullBurstLimit: 1
asyncChannelSize: 100
pullImageSecretForDaemonset:

csiPlugin:
  hostNetwork: false
  resources: {}
  image:
    tag: ""
    repository: docker.io/warmmetal/csi-image
    pullPolicy: IfNotPresent
  livenessProbe:
    httpGet:
      path: /healthz
      port: metrics
    failureThreshold: 5
    initialDelaySeconds: 10
    timeoutSeconds: 10
    periodSeconds: 60
csiLivenessProbe:
  resources: {}
  image:
    repository: registry.k8s.io/sig-storage/livenessprobe
    tag: v2.12.0
    pullPolicy: IfNotPresent
csiNodeDriverRegistrar:
  resources: {}
  image:
    repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
    tag: v2.10.0
    pullPolicy: IfNotPresent
csiExternalProvisioner:
  resources: {}
  image:
    repository: registry.k8s.io/sig-storage/csi-provisioner
    tag: v4.0.0
    pullPolicy: IfNotPresent

tolerations: {}
affinity: {}
nodeSelector: {}

fullnameOverride: ""

podMonitor:
  enabled: true
  interval: 30s
  timeout: 10s

containerd:
  startupTimeout: 20s
